language: node_js
node_js:
  - '8.9'
  - '9.4'
matrix:
  fast_finish: true
before_install: npm install -g grunt-cli
install:
  - npm install
  - npm install -g npm
notifications:
    email:
        on_failure: always
