language: node_js
node_js:
  - '8.9'
  - '9.4'
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin/grunt-cli
before_install: npm install -g grunt-cli
install:
  - npm install --no-optional
notifications:
    email:
        on_failure: always
sudo: false
