language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
matrix:
  allow_failures:
    - node_js: "iojs"
  fast_finish: true
before_install: npm install -g grunt-cli
install: npm install
#after_script: "istanbul cover ./all-tests.js"
